import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ThapaFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Conheça o ThapaFit!
        </h1>

        <h2 className={styles.subtitle}>O aplicativo que chegou para revolucionar o seu treino!</h2>

        <h3>Perfeito para instrutores e atletas!</h3>

        <h3>Tenha em suas maos o acompanhamento de seu instrutor e melhore sua performance!</h3>

        <div className={styles.grid}>
          <a className={styles.card}>
            <Link href="/sobre">
              <h2>O que e ThapaFit?</h2>
            </Link>
            <p>Descubra uma nova forma de treinar e veja performance aumentar!</p>
          </a>

          <a className={styles.card}>
            <Link href="/funcionamento">
              <h2>Como funciona?</h2>
            </Link>
            <p>Acompanhe em tempo real o desenvolvimento de seu treino.</p>
          </a>

          <a className={styles.card}>
            <Link href="/criadores">
              <h2>Quem faz o ThapaFit?</h2>
            </Link>
            <p>Conheca os desenvolvedores que criaram o ThapaFit!</p>
          </a>

          <a className={styles.card}>
            <Link href="/tecnico">
              <h2>Parte Tecnica</h2>
            </Link>
            <p>
              Saiba como foi feito o ThapaFit e veja o nosso plano de negocio!  
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
